import { DelayedError, Worker } from 'bullmq';
import { connection,enqueueEmail } from './email.queue.js';
import { prisma } from '../db/prisma.js';
import { env } from '../config/env.js';
import { indexEmail,sendThroughEthereal } from '../services/email.service.js';
import { notifyRateLimit } from '../services/slack.service.js';
const reserve= `local now=tonumber(ARGV[1]); local limit=tonumber(ARGV[2]); local spacing=tonumber(ARGV[3]); local id=ARGV[4]; local key=KEYS[1]; redis.call('ZREMRANGEBYSCORE',key,0,now-3600000); local count=redis.call('ZCARD',key); local last=redis.call('ZRANGE',key,-1,-1,'WITHSCORES'); local nextAllowed=now; if #last>0 then nextAllowed=math.max(nextAllowed,tonumber(last[2])+spacing) end; if count>=limit then local oldest=redis.call('ZRANGE',key,0,0,'WITHSCORES'); nextAllowed=math.max(nextAllowed,tonumber(oldest[2])+3600000); local notify=redis.call('SET',KEYS[2],'1','NX','EX',3600); return {nextAllowed-now,1,notify and 1 or 0} end; if nextAllowed>now then return {nextAllowed-now,0,0} end; redis.call('ZADD',key,now,id); redis.call('PEXPIRE',key,7200000); return {0,0,0}`;
const processingLeaseMs=120000;
export function createEmailWorker(){return new Worker('emails',async job=>{
 const email=await prisma.email.findUnique({where:{id:job.data.emailId},include:{sender:true,campaign:{include:{user:true,attachments:true}}}});if(!email||email.status==='sent'||email.status==='failed')return;
 if(email.status==='processing'&&email.processingAt){const leaseWait=processingLeaseMs-(Date.now()-email.processingAt.getTime());if(leaseWait>0){await job.moveToDelayed(Date.now()+leaseWait,job.token!);throw new DelayedError();}}
 const now=Date.now();const spacing=Math.max(env.MIN_EMAIL_DELAY_MS,email.campaign.delayBetweenEmails);const decision=await connection.eval(reserve,2,`rate:${email.senderId}`,`rate-notified:${email.senderId}`,now,email.campaign.hourlyLimit,spacing,`${email.id}:${job.attemptsMade}`) as [number,number,number];const wait=Number(decision[0]);
 if(wait>0){if(Number(decision[2])===1){const queued=await prisma.email.count({where:{senderId:email.senderId,status:'scheduled'}});await notifyRateLimit(email.campaign.userId,email.sender.email,email.campaign.hourlyLimit,wait,queued)}const rescheduledAt=new Date(now+wait);await prisma.email.updateMany({where:{id:email.id,status:'scheduled'},data:{scheduledAt:rescheduledAt}});await job.moveToDelayed(rescheduledAt.getTime(),job.token!);throw new DelayedError();}
 const claimed=await prisma.email.updateMany({where:{id:email.id,OR:[{status:'scheduled'},{status:'processing',processingAt:{lte:new Date(Date.now()-processingLeaseMs)}}]},data:{status:'processing',processingAt:new Date(),attempts:{increment:1}}});if(!claimed.count)return;
 try{const sent=await sendThroughEthereal({from:`${email.sender.displayName} <${email.sender.email}>`,to:email.recipient,subject:email.subject,text:email.body,html:email.htmlBody??undefined,attachments:email.campaign.attachments});const updated=await prisma.email.update({where:{id:email.id},data:{status:'sent',processingAt:null,sentAt:new Date(),providerMessageId:sent.messageId,errorMessage:null}});await indexEmail(updated)}catch(error){const message=error instanceof Error?error.message:'Unknown SMTP error';await prisma.email.update({where:{id:email.id},data:{status:'scheduled',processingAt:null,errorMessage:message}});throw error;}
},{connection,concurrency:env.WORKER_CONCURRENCY,lockDuration:150000});}
