import express from 'express';import cors from 'cors';import session from 'express-session';import {RedisStore} from 'connect-redis';import passport from 'passport';import {Strategy as GoogleStrategy} from 'passport-google-oauth20';import {ExpressAdapter} from '@bull-board/express';import {createBullBoard} from '@bull-board/api';import {BullMQAdapter} from '@bull-board/api/bullMQAdapter';
import helmet from 'helmet';
import { z } from 'zod';
import { hashPassword, verifyPassword } from './services/password.js';
import {env} from './config/env.js';import {connection,emailQueue} from './queues/email.queue.js';import {prisma} from './db/prisma.js';import api from './routes/api.js';import {saveSlack} from './services/slack.service.js';
if(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_CALLBACK_URL){passport.use(new GoogleStrategy({clientID:env.GOOGLE_CLIENT_ID,clientSecret:env.GOOGLE_CLIENT_SECRET,callbackURL:env.GOOGLE_CALLBACK_URL,state:true},async(_at,_rt,profile,done)=>{try{const email=profile.emails?.[0]?.value;if(!email)return done(new Error('Google did not provide an email'));const user=await prisma.user.upsert({where:{googleId:profile.id},create:{googleId:profile.id,email,name:profile.displayName||email,avatarUrl:profile.photos?.[0]?.value},update:{email,name:profile.displayName||email,avatarUrl:profile.photos?.[0]?.value}});done(null,user)}catch(e){done(e as Error)}}))}
const app=express();app.set('trust proxy',1);app.use(helmet());app.use(cors({origin:env.FRONTEND_URL,credentials:true}));app.use(express.json({limit:'8mb'}));app.use(session({store:new RedisStore({client:connection as never}),secret:env.SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:env.COOKIE_SECURE==='true'?'none':'lax',secure:env.COOKIE_SECURE==='true',maxAge:7*86400000}}));app.use(passport.initialize());app.use(passport.session());
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.post('/api/auth/register',async(req,res,next)=>{const parsed=z.object({email:z.string().email().max(254),name:z.string().trim().min(1).max(100),password:z.string().min(8).max(128)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Enter a valid name, email, and password of at least 8 characters.'});try{const user=await prisma.user.create({data:{email:parsed.data.email.toLowerCase(),name:parsed.data.name,passwordHash:await hashPassword(parsed.data.password)},select:{id:true,name:true,email:true,avatarUrl:true}});req.session.regenerate(error=>{if(error)return next(error);req.session.userId=user.id;req.session.save(saveError=>saveError?next(saveError):res.status(201).json({...user,hasPassword:true}))})}catch(error){if((error as {code?:string}).code==='P2002')return res.status(409).json({error:'An account with that email already exists.'});next(error)}});
app.post('/api/auth/login',async(req,res,next)=>{const parsed=z.object({email:z.string().email().max(254),password:z.string().min(1).max(128)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Enter a valid email and password.'});try{const user=await prisma.user.findUnique({where:{email:parsed.data.email.toLowerCase()}});if(!user?.passwordHash||!await verifyPassword(parsed.data.password,user.passwordHash))return res.status(401).json({error:'Invalid email or password.'});req.session.regenerate(error=>{if(error)return next(error);req.session.userId=user.id;req.session.save(saveError=>saveError?next(saveError):res.json({id:user.id,name:user.name,email:user.email,avatarUrl:user.avatarUrl,hasPassword:true}))})}catch(error){next(error)}});
app.get('/api/auth/session',async(req,res,next)=>{if(!req.session.userId)return res.json({authenticated:false});try{const user=await prisma.user.findUnique({where:{id:req.session.userId},select:{id:true,name:true,email:true,avatarUrl:true,passwordHash:true}});res.json(user?{authenticated:true,user:{id:user.id,name:user.name,email:user.email,avatarUrl:user.avatarUrl,hasPassword:Boolean(user.passwordHash)}}:{authenticated:false})}catch(error){next(error)}});
app.get('/api/auth/google',passport.authenticate('google',{scope:['profile','email'],session:false}));app.get('/api/auth/google/callback',passport.authenticate('google',{failureRedirect:`${env.FRONTEND_URL}/?error=google_auth`,session:false}),(req,res,next)=>{
  console.info('Google OAuth callback reached');
  if(!req.user){console.info('Google OAuth user authenticated: false');return res.redirect(`${env.FRONTEND_URL}/?error=google_auth`)}
  console.info('Google OAuth user authenticated: true');
  req.session.userId=(req.user as {id:string}).id;
  console.info(`Google OAuth session ID exists: ${Boolean(req.sessionID)}`);
  console.info('Google OAuth session save started');
  req.session.save(error=>{
    if(error){console.error('Google OAuth session save failed');return res.status(500).json({error:'Could not persist login session.'})}
    console.info('Google OAuth session save succeeded');
    res.redirect(env.FRONTEND_URL);
  });
});app.post('/api/auth/logout',(req,res)=>req.session.destroy(error=>{if(error)return res.status(500).json({error:'Could not sign out.'});res.clearCookie('connect.sid');res.status(204).end()}));app.use('/api',api);
app.get('/api/slack/connect',(req,res,next)=>{if(!req.session.userId)return res.status(401).json({error:'Authentication required'});if(!env.SLACK_CLIENT_ID||!env.SLACK_CALLBACK_URL)return res.status(503).json({error:'Slack OAuth is not configured'});const state=crypto.randomUUID();req.session.slackState=state;res.redirect(`https://slack.com/oauth/v2/authorize?client_id=${env.SLACK_CLIENT_ID}&scope=chat:write,im:write&redirect_uri=${encodeURIComponent(env.SLACK_CALLBACK_URL)}&state=${state}`)});
app.get('/api/slack/callback',async(req,res,next)=>{try{if(req.query.error)throw new Error(String(req.query.error));if(!req.session.userId||req.query.state!==req.session.slackState)throw new Error('Invalid Slack OAuth state');const response=await fetch('https://slack.com/api/oauth.v2.access',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.SLACK_CLIENT_ID??'',client_secret:env.SLACK_CLIENT_SECRET??'',code:String(req.query.code??''),redirect_uri:env.SLACK_CALLBACK_URL??''})});const body=await response.json() as {ok:boolean;access_token?:string;team?:{id?:string;name?:string};authed_user?:{id?:string};error?:string};if(!body.ok||!body.access_token)throw new Error(body.error??'Slack OAuth failed');await saveSlack(req.session.userId,body.access_token,body.team?.id??'',body.team?.name??'Slack',body.authed_user?.id);res.redirect(`${env.FRONTEND_URL}/?slack=connected`)}catch(error){next(error)}});
const serverAdapter=new ExpressAdapter();serverAdapter.setBasePath('/admin/queues');createBullBoard({queues:[new BullMQAdapter(emailQueue)],serverAdapter});app.use('/admin/queues',(req,res,next)=>req.session.userId?next():res.status(401).send('Authentication required'));app.use('/admin/queues',serverAdapter.getRouter());app.use((err:Error,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
export {app};
