import { Router } from 'express';
import { z } from 'zod';
import type { Prisma } from '@prisma/client';
import { prisma } from '../db/prisma.js';
import { enqueuePendingEmails } from '../queues/outbox.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncHandler } from '../middleware/async-handler.js';
import { elastic } from '../services/email.service.js';
import { disconnectSlack } from '../services/slack.service.js';
import { env } from '../config/env.js';
import { emailIdempotencyKey, uniqueRecipients } from '../services/scheduling.js';
import { hashPassword } from '../services/password.js';
const router=Router();router.use(requireAuth);
router.get('/me',asyncHandler(async(req,res)=>{const user=await prisma.user.findUnique({where:{id:req.session.userId},select:{id:true,name:true,email:true,avatarUrl:true,passwordHash:true}});res.json(user?{id:user.id,name:user.name,email:user.email,avatarUrl:user.avatarUrl,hasPassword:Boolean(user.passwordHash)}:null)}));
router.post('/auth/password',asyncHandler(async(req,res)=>{const parsed=z.object({password:z.string().min(8).max(128)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Password must be between 8 and 128 characters.'});await prisma.user.update({where:{id:req.session.userId},data:{passwordHash:await hashPassword(parsed.data.password)}});res.status(204).end()}));
router.post('/senders',asyncHandler(async(req,res)=>{const parsed=z.object({email:z.string().email(),displayName:z.string().min(1).max(100)}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.flatten()});const sender=await prisma.sender.upsert({where:{userId_email:{userId:req.session.userId!,email:parsed.data.email}},create:{userId:req.session.userId!,...parsed.data},update:{displayName:parsed.data.displayName,active:true}});res.status(201).json(sender)}));
router.get('/senders',asyncHandler(async(req,res)=>{res.json(await prisma.sender.findMany({where:{userId:req.session.userId}}))}));
const attachmentSchema=z.object({filename:z.string().min(1).max(255),contentType:z.string().min(1).max(150),contentBase64:z.string().min(1).max(7_000_000).regex(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/)});
const campaignSchema=z.object({subject:z.string().min(1).max(300),body:z.string().min(1),htmlBody:z.string().optional(),attachments:z.array(attachmentSchema).max(5).optional(),recipients:z.array(z.string().email()).min(1).max(10000),senderId:z.string().optional(),startTime:z.string().datetime().optional(),delayBetweenEmails:z.number().int().min(0).max(3600000).optional(),hourlyLimit:z.number().int().positive().max(10000).optional(),idempotencyKey:z.string().min(8).max(200).optional()});
router.post('/campaigns',async(req,res,next)=>{const parsed=campaignSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.flatten()});try{const userId=req.session.userId!;const sender=parsed.data.senderId?await prisma.sender.findFirst({where:{id:parsed.data.senderId,userId,active:true}}):await prisma.sender.findFirst({where:{userId,active:true}});if(!sender)return res.status(400).json({error:'Add an active sender before scheduling.'});const attachments=parsed.data.attachments??[];if(attachments.reduce((sum,file)=>sum+Buffer.from(file.contentBase64,'base64').length,0)>5*1024*1024)return res.status(400).json({error:'Attachments must total no more than 5 MB.'});const recipients=uniqueRecipients(parsed.data.recipients);const startTime=new Date(parsed.data.startTime??Date.now()),delay=parsed.data.delayBetweenEmails??env.MIN_EMAIL_DELAY_MS,hourlyLimit=parsed.data.hourlyLimit??env.DEFAULT_HOURLY_LIMIT;const campaign=await prisma.$transaction(async tx=>{const created=await tx.campaign.create({data:{userId,subject:parsed.data.subject,body:parsed.data.body,startTime,delayBetweenEmails:delay,hourlyLimit,attachments:{create:attachments}}});const emails=await tx.email.createManyAndReturn({data:recipients.map((recipient,i)=>({campaignId:created.id,senderId:sender.id,recipient,subject:parsed.data.subject,body:parsed.data.body,htmlBody:parsed.data.htmlBody,scheduledAt:new Date(startTime.getTime()+i*delay),idempotencyKey:emailIdempotencyKey(created.id,i,recipient,parsed.data.idempotencyKey)}))});await tx.queueOutbox.createMany({data:emails.map(email=>({userId,emailId:email.id}))});return {created,emails}});const queue=await enqueuePendingEmails();const emails=await prisma.email.findMany({where:{id:{in:campaign.emails.map(email=>email.id)}},include:emailInclude});res.status(201).json({campaign:campaign.created,emails:emails.map(serializeEmail),queuePending:queue.pending})}catch(error){next(error)}});
const emailInclude={sender:true as const,campaign:{select:{id:true,userId:true,subject:true,startTime:true,delayBetweenEmails:true,hourlyLimit:true,attachments:{select:{id:true,filename:true,contentType:true,contentBase64:true}}}}};
function serializeEmail<T extends {campaign?:{attachments?:{contentBase64:string}[]}|null}>(email:T){if(!email.campaign)return email;const attachments=email.campaign.attachments?.map(({contentBase64,...file})=>({...file,size:Buffer.from(contentBase64,'base64').byteLength}));return {...email,campaign:{...email.campaign,...(attachments?{attachments}: {})}}}
const emailViews=['all','starred','archived','trash','scheduled','sent'] as const;
const emailQuerySchema=z.object({view:z.enum(emailViews).default('all'),status:z.enum(['scheduled','processing','sent','failed']).optional(),page:z.coerce.number().int().min(1).optional(),limit:z.coerce.number().int().min(1).max(50).optional(),q:z.string().trim().max(300).optional(),dateFrom:z.string().datetime().optional(),dateTo:z.string().datetime().optional()});
function emailWhere(userId:string,query:z.infer<typeof emailQuerySchema>):Prisma.EmailWhereInput{
  const where:Prisma.EmailWhereInput={campaign:{userId},...(query.status?{status:query.status}:{})};
  if(query.view==='trash') where.deletedAt={not:null};
  else { where.deletedAt=null; if(query.view==='archived') where.isArchived=true; else if(query.view==='starred') Object.assign(where,{isArchived:false,isStarred:true}); else if(query.view==='scheduled') Object.assign(where,{isArchived:false,status:{in:['scheduled','processing']}}); else if(query.view==='sent') Object.assign(where,{isArchived:false,status:{in:['sent','failed']}}); else where.isArchived=false; }
  if(query.q){const q=query.q;where.OR=[{recipient:{contains:q,mode:'insensitive'}},{subject:{contains:q,mode:'insensitive'}},{body:{contains:q,mode:'insensitive'}},{sender:{email:{contains:q,mode:'insensitive'}}},{sender:{displayName:{contains:q,mode:'insensitive'}}}];}
  if(query.dateFrom||query.dateTo){const dateField=query.view==='scheduled'?'scheduledAt':query.view==='sent'?'sentAt':'createdAt';where[dateField]={...(query.dateFrom?{gte:new Date(query.dateFrom)}:{}),...(query.dateTo?{lt:new Date(query.dateTo)}:{})};}
  return where;
}
function emailOrder(view:typeof emailViews[number]):Prisma.EmailOrderByWithRelationInput[]{if(view==='sent')return [{sentAt:'desc'},{createdAt:'desc'}];if(view==='scheduled'||view==='all')return [{scheduledAt:'asc'},{id:'asc'}];return [{createdAt:'desc'},{id:'desc'}];}
router.get('/emails',asyncHandler(async(req,res)=>{const parsed=emailQuerySchema.safeParse(req.query);if(!parsed.success)return res.status(400).json({error:parsed.error.flatten()});const query=parsed.data,where=emailWhere(req.session.userId!,query),orderBy=emailOrder(query.view),paginate=query.page!==undefined||query.limit!==undefined;if(!paginate){const emails=await prisma.email.findMany({where,include:emailInclude,orderBy,take:1000});return res.json(emails.map(serializeEmail));}const pageSize=query.limit??50,totalCount=await prisma.email.count({where}),totalPages=Math.ceil(totalCount/pageSize),currentPage=totalPages?Math.min(query.page??1,totalPages):1,emails=await prisma.email.findMany({where,include:emailInclude,orderBy,skip:(currentPage-1)*pageSize,take:pageSize});res.json({emails:emails.map(serializeEmail),currentPage,pageSize,totalCount,totalPages,hasNextPage:currentPage<totalPages,hasPreviousPage:currentPage>1});}));
const bulkSchema=z.object({ids:z.array(z.string().min(1)).min(1).max(50),action:z.enum(['archive','unarchive','star','unstar','trash','restore','permanent-delete'])});
router.patch('/emails/bulk',asyncHandler(async(req,res)=>{const parsed=bulkSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:parsed.error.flatten()});const {ids,action}=parsed.data,userId=req.session.userId!,owned=await prisma.email.findMany({where:{id:{in:ids},campaign:{userId}},select:{id:true,campaignId:true}});if(owned.length!==ids.length)return res.status(404).json({error:'One or more emails were not found'});let count=0;if(action==='permanent-delete'){await prisma.$transaction(async tx=>{const deleted=await tx.email.deleteMany({where:{id:{in:ids},campaign:{userId}}});count=deleted.count;await tx.campaign.deleteMany({where:{userId,id:{in:owned.map(email=>email.campaignId)},emails:{none:{}}}});});}else{const data=action==='archive'?{isArchived:true}:action==='unarchive'?{isArchived:false}:action==='star'?{isStarred:true}:action==='unstar'?{isStarred:false}:action==='trash'?{deletedAt:new Date()}:{deletedAt:null};const result=await prisma.email.updateMany({where:{id:{in:ids},campaign:{userId}},data});count=result.count;}if(action==='permanent-delete'){await Promise.all(ids.map(async id=>{try{await elastic.delete({index:'emails',id});}catch(error){if((error as {meta?:{statusCode?:number}}).meta?.statusCode!==404)console.error('Search document deletion failed',error);}}));}res.json({count});}));
router.patch('/emails/:id/star',asyncHandler(async(req,res)=>{const id=String(req.params.id);const parsed=z.object({starred:z.boolean()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'starred must be a boolean'});const result=await prisma.email.updateMany({where:{id,campaign:{userId:req.session.userId},deletedAt:null},data:{isStarred:parsed.data.starred}});if(!result.count)return res.status(404).json({error:'Email not found'});res.json({id,isStarred:parsed.data.starred})}));
router.patch('/emails/:id/archive',asyncHandler(async(req,res)=>{const parsed=z.object({archived:z.boolean().optional()}).optional().safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'archived must be a boolean'});const result=await prisma.email.updateMany({where:{id:String(req.params.id),campaign:{userId:req.session.userId},deletedAt:null},data:{isArchived:parsed.data?.archived??true}});if(!result.count)return res.status(404).json({error:'Email not found'});res.status(204).end()}));
router.patch('/emails/:id/trash',asyncHandler(async(req,res)=>{const result=await prisma.email.updateMany({where:{id:String(req.params.id),campaign:{userId:req.session.userId},deletedAt:null},data:{deletedAt:new Date()}});if(!result.count)return res.status(404).json({error:'Email not found'});res.status(204).end()}));
router.patch('/emails/:id/restore',asyncHandler(async(req,res)=>{const result=await prisma.email.updateMany({where:{id:String(req.params.id),campaign:{userId:req.session.userId},deletedAt:{not:null}},data:{deletedAt:null}});if(!result.count)return res.status(404).json({error:'Email not found'});res.status(204).end()}));
router.delete('/emails/:id/permanent',asyncHandler(async(req,res)=>{const id=String(req.params.id),email=await prisma.email.findFirst({where:{id,campaign:{userId:req.session.userId},deletedAt:{not:null}},select:{id:true,campaignId:true}});if(!email)return res.status(404).json({error:'Email not found'});await prisma.$transaction(async tx=>{await tx.email.delete({where:{id}});await tx.campaign.deleteMany({where:{id:email.campaignId,userId:req.session.userId,emails:{none:{}}}})});try{await elastic.delete({index:'emails',id})}catch(error){if((error as {meta?:{statusCode?:number}}).meta?.statusCode!==404)console.error('Search document deletion failed',error)}res.status(204).end()}));
router.delete('/emails/:id',asyncHandler(async(req,res)=>{const result=await prisma.email.updateMany({where:{id:String(req.params.id),campaign:{userId:req.session.userId},deletedAt:null},data:{deletedAt:new Date()}});if(!result.count)return res.status(404).json({error:'Email not found'});res.status(204).end()}));
router.patch('/emails/:id/star',asyncHandler(async(req,res)=>{const id=String(req.params.id);const parsed=z.object({starred:z.boolean()}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'starred must be a boolean'});const result=await prisma.email.updateMany({where:{id,campaign:{userId:req.session.userId}},data:{isStarred:parsed.data.starred}});if(!result.count)return res.status(404).json({error:'Email not found'});res.json({id,isStarred:parsed.data.starred})}));
router.patch('/emails/:id/archive',asyncHandler(async(req,res)=>{const parsed=z.object({archived:z.boolean().optional()}).optional().safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'archived must be a boolean'});const result=await prisma.email.updateMany({where:{id:String(req.params.id),campaign:{userId:req.session.userId}},data:{isArchived:parsed.data?.archived??true}});if(!result.count)return res.status(404).json({error:'Email not found'});res.status(204).end()}));
router.delete('/emails/:id',asyncHandler(async(req,res)=>{const email=await prisma.email.findFirst({where:{id:String(req.params.id),campaign:{userId:req.session.userId}},select:{id:true}});if(!email)return res.status(404).json({error:'Email not found'});await prisma.email.delete({where:{id:email.id}});try{await elastic.delete({index:'emails',id:email.id})}catch(error){if((error as {meta?:{statusCode?:number}}).meta?.statusCode!==404)console.error('Search document deletion failed',error)}res.status(204).end()}));
router.get('/emails/:id/attachments/:attachmentId',asyncHandler(async(req,res)=>{const attachment=await prisma.campaignAttachment.findFirst({where:{id:String(req.params.attachmentId),campaign:{userId:req.session.userId,emails:{some:{id:String(req.params.id)}}}}});if(!attachment)return res.status(404).json({error:'Attachment not found'});const content=Buffer.from(attachment.contentBase64,'base64');res.type(attachment.contentType);if(attachment.contentType.startsWith('image/'))res.set('Content-Disposition','inline');else res.attachment(attachment.filename);res.send(content)}));
router.get('/search',asyncHandler(async(req,res)=>{const parsed=z.string().trim().min(1).max(300).safeParse(req.query.q);if(!parsed.success)return res.status(400).json({error:'A non-empty search query is required'});const query=emailQuerySchema.safeParse({...req.query,view:req.query.view??'all',q:parsed.data});if(!query.success)return res.status(400).json({error:query.error.flatten()});const params=query.data,baseWhere=emailWhere(req.session.userId!,params),textWhere=baseWhere.OR;delete baseWhere.OR;let indexedIds:string[]=[];try{const found=await elastic.search({index:'emails',size:5000,query:{multi_match:{query:parsed.data,fields:['recipient^3','senderEmail^3','senderName^2','subject^3','body'],fuzziness:'AUTO'}}});indexedIds=found.hits.hits.map(hit=>String(hit._id));}catch(error){console.error('Elasticsearch search failed; using PostgreSQL matches',error)}const where:Prisma.EmailWhereInput=indexedIds.length?{AND:[baseWhere,{OR:[...(textWhere??[]),{id:{in:indexedIds}}]}]}:{...baseWhere,OR:textWhere??[]};const paginate=params.page!==undefined||params.limit!==undefined;if(!paginate){const records=await prisma.email.findMany({where,include:emailInclude,take:1000,orderBy:{createdAt:'desc'}});return res.json(records.map(serializeEmail));}const pageSize=params.limit??50,totalCount=await prisma.email.count({where}),totalPages=Math.ceil(totalCount/pageSize),currentPage=totalPages?Math.min(params.page??1,totalPages):1,records=await prisma.email.findMany({where,include:emailInclude,skip:(currentPage-1)*pageSize,take:pageSize,orderBy:{createdAt:'desc'}});res.json({emails:records.map(serializeEmail),currentPage,pageSize,totalCount,totalPages,hasNextPage:currentPage<totalPages,hasPreviousPage:currentPage>1});}));
router.get('/slack',asyncHandler(async(req,res)=>{res.json({connected:!!await prisma.slackConnection.findUnique({where:{userId:req.session.userId}})})}));
router.delete('/slack',asyncHandler(async(req,res)=>{await disconnectSlack(req.session.userId!);res.status(204).end()}));
router.get('/queue',asyncHandler(async(_req,res)=>{const {emailQueue}=await import('../queues/email.queue.js');res.json(await Promise.all(['waiting','delayed','active','completed','failed'].map(async state=>({state,count:await emailQueue.getJobCountByTypes(state as never)}))))}));
export default router;
