import { createCipheriv,createDecipheriv,randomBytes } from 'node:crypto';
import { env } from '../config/env.js';
import { prisma } from '../db/prisma.js';
function encryptionKey(){if(!env.SLACK_TOKEN_ENCRYPTION_KEY)throw new Error('Set SLACK_TOKEN_ENCRYPTION_KEY before connecting Slack');return Buffer.from(env.SLACK_TOKEN_ENCRYPTION_KEY)}
function seal(token:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(),iv);const data=Buffer.concat([cipher.update(token,'utf8'),cipher.final()]);return `${iv.toString('hex')}:${cipher.getAuthTag().toString('hex')}:${data.toString('hex')}`}
function open(value:string){const [iv,tag,data]=value.split(':');const decipher=createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(iv,'hex'));decipher.setAuthTag(Buffer.from(tag,'hex'));return Buffer.concat([decipher.update(Buffer.from(data,'hex')),decipher.final()]).toString()}
export async function saveSlack(userId:string,token:string,teamId:string,teamName:string,slackUserId?:string){return prisma.slackConnection.upsert({where:{userId},create:{userId,accessToken:seal(token),teamId,teamName,slackUserId},update:{accessToken:seal(token),teamId,teamName,slackUserId,connectedAt:new Date()}})}
export async function notifyRateLimit(userId:string,senderEmail:string,hourlyLimit:number,waitMs:number,queued:number){try{const connection=await prisma.slackConnection.findUnique({where:{userId}});if(!connection||!connection.slackUserId)return;const headers={authorization:`Bearer ${open(connection.accessToken)}`,'content-type':'application/json'};const opened=await fetch('https://slack.com/api/conversations.open',{method:'POST',headers,body:JSON.stringify({users:connection.slackUserId})});const conversation=await opened.json() as {ok:boolean;channel?:{id:string}};if(!conversation.ok||!conversation.channel?.id)throw new Error('Slack could not open a direct message with the connected user');const waitMinutes=Math.max(1,Math.ceil(waitMs/60000));const sent=await fetch('https://slack.com/api/chat.postMessage',{method:'POST',headers,body:JSON.stringify({channel:conversation.channel.id,text:`Hourly sender limit reached for ${senderEmail}: ${hourlyLimit} emails per rolling hour. The next available window is in about ${waitMinutes} minute${waitMinutes===1?'':'s'}. ${queued} email${queued===1?' remains':'s remain'} queued and rescheduled.`})});const result=await sent.json() as {ok:boolean;error?:string};if(!result.ok)throw new Error(result.error??'Slack rejected notification')}catch(error){console.error('Slack notification failed',error)}}
export async function disconnectSlack(userId:string){const existing=await prisma.slackConnection.findUnique({where:{userId}});if(existing){try{await fetch('https://slack.com/api/auth.revoke',{method:'POST',headers:{authorization:`Bearer ${open(existing.accessToken)}`}})}catch(error){console.error('Slack token revoke failed',error)}await prisma.slackConnection.delete({where:{userId}})}}

